name: godtinnhold_Test
favicon: null
layout_spectrum: 0.889017699053511
typography_spectrum: 0.9694679367821664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3213483588770032
  lightness: 0.021824853029102087
  saturation: 0.8077209391631186
  rhythmicContrast: 0.2678946857340634
purpose: []
